// Generated by gencpp from file turtlebot3_gazebo/envResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_ENVRESPONSE_H
#define TURTLEBOT3_GAZEBO_MESSAGE_ENVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_gazebo
{
template <class ContainerAllocator>
struct envResponse_
{
  typedef envResponse_<ContainerAllocator> Type;

  envResponse_()
    : result()  {
    }
  envResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> const> ConstPtr;

}; // struct envResponse_

typedef ::turtlebot3_gazebo::envResponse_<std::allocator<void> > envResponse;

typedef boost::shared_ptr< ::turtlebot3_gazebo::envResponse > envResponsePtr;
typedef boost::shared_ptr< ::turtlebot3_gazebo::envResponse const> envResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_gazebo::envResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_gazebo::envResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::envResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_gazebo::envResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::envResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::turtlebot3_gazebo::envResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_gazebo/envResponse";
  }

  static const char* value(const ::turtlebot3_gazebo::envResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::turtlebot3_gazebo::envResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct envResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_gazebo::envResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_gazebo::envResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_ENVRESPONSE_H
