// Generated by gencpp from file turtlebot3_gazebo/envRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_ENVREQUEST_H
#define TURTLEBOT3_GAZEBO_MESSAGE_ENVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_gazebo
{
template <class ContainerAllocator>
struct envRequest_
{
  typedef envRequest_<ContainerAllocator> Type;

  envRequest_()
    : info()  {
    }
  envRequest_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> const> ConstPtr;

}; // struct envRequest_

typedef ::turtlebot3_gazebo::envRequest_<std::allocator<void> > envRequest;

typedef boost::shared_ptr< ::turtlebot3_gazebo::envRequest > envRequestPtr;
typedef boost::shared_ptr< ::turtlebot3_gazebo::envRequest const> envRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_gazebo::envRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_gazebo::envRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::envRequest_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_gazebo::envRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::envRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::turtlebot3_gazebo::envRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_gazebo/envRequest";
  }

  static const char* value(const ::turtlebot3_gazebo::envRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string info\n"
;
  }

  static const char* value(const ::turtlebot3_gazebo::envRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct envRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_gazebo::envRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_gazebo::envRequest_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_ENVREQUEST_H
