// Generated by gencpp from file turtlebot3_gazebo/goalRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_GOALREQUEST_H
#define TURTLEBOT3_GAZEBO_MESSAGE_GOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_gazebo
{
template <class ContainerAllocator>
struct goalRequest_
{
  typedef goalRequest_<ContainerAllocator> Type;

  goalRequest_()
    : info(0)  {
    }
  goalRequest_(const ContainerAllocator& _alloc)
    : info(0)  {
  (void)_alloc;
    }



   typedef int64_t _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct goalRequest_

typedef ::turtlebot3_gazebo::goalRequest_<std::allocator<void> > goalRequest;

typedef boost::shared_ptr< ::turtlebot3_gazebo::goalRequest > goalRequestPtr;
typedef boost::shared_ptr< ::turtlebot3_gazebo::goalRequest const> goalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "064189280842713a5615fa0211d3cc1c";
  }

  static const char* value(const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x064189280842713aULL;
  static const uint64_t static_value2 = 0x5615fa0211d3cc1cULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_gazebo/goalRequest";
  }

  static const char* value(const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 info\n"
;
  }

  static const char* value(const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_gazebo::goalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_gazebo::goalRequest_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<int64_t>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_GOALREQUEST_H
