// Generated by gencpp from file turtlebot3_gazebo/goal.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_GOAL_H
#define TURTLEBOT3_GAZEBO_MESSAGE_GOAL_H

#include <ros/service_traits.h>


#include <turtlebot3_gazebo/goalRequest.h>
#include <turtlebot3_gazebo/goalResponse.h>


namespace turtlebot3_gazebo
{

struct goal
{

typedef goalRequest Request;
typedef goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goal
} // namespace turtlebot3_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_gazebo::goal > {
  static const char* value()
  {
    return "77ff7a94d88edbfc6dc3d724b3c2eff1";
  }

  static const char* value(const ::turtlebot3_gazebo::goal&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_gazebo::goal > {
  static const char* value()
  {
    return "turtlebot3_gazebo/goal";
  }

  static const char* value(const ::turtlebot3_gazebo::goal&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_gazebo::goalRequest> should match
// service_traits::MD5Sum< ::turtlebot3_gazebo::goal >
template<>
struct MD5Sum< ::turtlebot3_gazebo::goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_gazebo::goal >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_gazebo::goalRequest> should match
// service_traits::DataType< ::turtlebot3_gazebo::goal >
template<>
struct DataType< ::turtlebot3_gazebo::goalRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_gazebo::goal >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_gazebo::goalResponse> should match
// service_traits::MD5Sum< ::turtlebot3_gazebo::goal >
template<>
struct MD5Sum< ::turtlebot3_gazebo::goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_gazebo::goal >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_gazebo::goalResponse> should match
// service_traits::DataType< ::turtlebot3_gazebo::goal >
template<>
struct DataType< ::turtlebot3_gazebo::goalResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_gazebo::goal >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_GOAL_H
