// Generated by gencpp from file turtlebot3_gazebo/skillsResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_SKILLSRESPONSE_H
#define TURTLEBOT3_GAZEBO_MESSAGE_SKILLSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_gazebo
{
template <class ContainerAllocator>
struct skillsResponse_
{
  typedef skillsResponse_<ContainerAllocator> Type;

  skillsResponse_()
    : result(0)  {
    }
  skillsResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct skillsResponse_

typedef ::turtlebot3_gazebo::skillsResponse_<std::allocator<void> > skillsResponse;

typedef boost::shared_ptr< ::turtlebot3_gazebo::skillsResponse > skillsResponsePtr;
typedef boost::shared_ptr< ::turtlebot3_gazebo::skillsResponse const> skillsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_gazebo/skillsResponse";
  }

  static const char* value(const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
"\n"
;
  }

  static const char* value(const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct skillsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_gazebo::skillsResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_SKILLSRESPONSE_H
