// Generated by gencpp from file turtlebot3_gazebo/skills.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_GAZEBO_MESSAGE_SKILLS_H
#define TURTLEBOT3_GAZEBO_MESSAGE_SKILLS_H

#include <ros/service_traits.h>


#include <turtlebot3_gazebo/skillsRequest.h>
#include <turtlebot3_gazebo/skillsResponse.h>


namespace turtlebot3_gazebo
{

struct skills
{

typedef skillsRequest Request;
typedef skillsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct skills
} // namespace turtlebot3_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_gazebo::skills > {
  static const char* value()
  {
    return "229397e1a56adaf3792840999a6595c1";
  }

  static const char* value(const ::turtlebot3_gazebo::skills&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_gazebo::skills > {
  static const char* value()
  {
    return "turtlebot3_gazebo/skills";
  }

  static const char* value(const ::turtlebot3_gazebo::skills&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_gazebo::skillsRequest> should match
// service_traits::MD5Sum< ::turtlebot3_gazebo::skills >
template<>
struct MD5Sum< ::turtlebot3_gazebo::skillsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_gazebo::skills >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::skillsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_gazebo::skillsRequest> should match
// service_traits::DataType< ::turtlebot3_gazebo::skills >
template<>
struct DataType< ::turtlebot3_gazebo::skillsRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_gazebo::skills >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::skillsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_gazebo::skillsResponse> should match
// service_traits::MD5Sum< ::turtlebot3_gazebo::skills >
template<>
struct MD5Sum< ::turtlebot3_gazebo::skillsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_gazebo::skills >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::skillsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_gazebo::skillsResponse> should match
// service_traits::DataType< ::turtlebot3_gazebo::skills >
template<>
struct DataType< ::turtlebot3_gazebo::skillsResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_gazebo::skills >::value();
  }
  static const char* value(const ::turtlebot3_gazebo::skillsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_GAZEBO_MESSAGE_SKILLS_H
